# Generated by Django 4.0.2 on 2022-03-16 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selectiveProcess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='sector_fo',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teste',
        ),
        migrations.AddField(
            model_name='candidate',
            name='first_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstSector', to='selectiveProcess.sector'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='second_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondSector', to='selectiveProcess.sector'),
        ),
    ]
