# Generated by Django 4.0.2 on 2022-03-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selectiveProcess', '0002_remove_candidate_sector_fo_remove_course_teste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_sector', to='selectiveProcess.sector'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_sector', to='selectiveProcess.sector'),
        ),
    ]
