# Generated by Django 4.0.2 on 2022-03-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectiveProcess', '0003_alter_candidate_first_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
