# Generated by Django 4.0.2 on 2022-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectiveProcess', '0004_candidate_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(upload_to=''),
        ),
    ]
