# Generated by Django 4.0.2 on 2022-03-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectiveProcess', '0006_alter_candidate_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
